name: Update Plugin Documentation

on:
  workflow_dispatch:  # Allows manual trigger from GitHub Actions UI

jobs:
  update-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Generate plugin documentation
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          python __scripts/generate_plugin_docs.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'docs: update public plugin documentation'
          title: 'Update Public Plugin Documentation'
          body: |
            ## Summary
            This PR updates the public plugin documentation by fetching the latest data from the Supabase database.

            ### Changes
            - Updated plugin pages in `public-plugins/` directory
            - Regenerated overview page with current plugin list
            - Updated `docs.json` navigation configuration

            ### Generated by
            GitHub Actions workflow: `update-plugin-docs.yml`

            ### Review checklist
            - [ ] Verify all plugin pages are present and correctly formatted
            - [ ] Check that the overview table includes all plugins
            - [ ] Ensure navigation in `docs.json` is correct
            - [ ] Review any new or updated plugin documentation
          branch: update-plugin-docs
          delete-branch: true
          labels: |
            documentation
            automated
